config/routes.rb
# typed: strict


Rails.application.routes.draw do
  resources :projects
  root 'static#index'
  get 'login', to: 'sessions#new'
  get 'portfolio', to: 'projects#index'
  get 'posts/list'
  get 'sessions/new'
  get 'setup/ubuntu'
  get 'setup/zsh'
  get 'setup/ruby'
  get 'setup/vscode'
  get 'setup/gnome'
  get 'setup/albert'
  get 'setup/index'
  get 'setup/misc'
  get 'setup/issues'
  get 'static/index'
  get 'static/aboutme'
  get 'contact', to: 'messages#new'
  get 'messages/new'
  post 'messages/create'
  resources :tags
  resources :sessions, only: %i[create new destroy]
  resources :posts
  get '/check.txt', to: proc { [200, {}, ['it_works']] }
  get 'google5ef096ebdd0ff65a.html', to: 'static#google5ef096ebdd0ff65a', layout: false
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
# typed: strict
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
end

app/controllers/tags_controller.rb
# typed: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]
  before_action :authentication_required!, except: %i[index show]

  # GET /tags
  def index
    @tags = Tag.all.order(name: :asc)
  end

  # GET /tags/1
  def show; end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = 'Tag was successfully created.'
      redirect_to @tag
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      flash[:success] = 'Tag was successfully updated.'
      redirect_to @tag
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    flash[:success] = 'Tag was successfully destroyed.'
    redirect_to tags_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find_by(name: params[:id]) || Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
# typed: strong
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<% provide(:title, "Edit Tag") %>
<%= render 'layouts/top_of_page' %>

<h1>Edit Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<% provide(:title, 'Tags') %>
<%= render 'layouts/post_tabs' %>
<h1>Tags</h1>
<div class="border-secondary pl-3 border-left">
  <table>
    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= link_to tag.name, tag %> <small> <%= pluralize(tag.posts.count, 'post') %></small></td>
  <% if admin? %>
          <td><%= link_to 'Edit', edit_tag_path(tag), class: "btn btn-sm btn-outline-warning" %></td>
          <td><%= link_to 'Destroy', tag, method: :delete, class: "btn btn-sm btn-outline-danger", data: { confirm: 'Are you sure?' } %></td>
    <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>



<p class="mt-1">
  <% if admin? %>
    <%= link_to 'New Tag', new_tag_path, class: "btn btn-sm btn-outline-info"%>
  <% end %>
</p>

app/views/tags/new.html.erb
<%= render 'layouts/top_of_page' %>
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<% provide(:title, 'Tags') %>
<%= render 'layouts/post_tabs' %>

<p>
  <h1><%= @tag.name %></h1>
  <small><%= pluralize(@tag.posts.count, 'post') %></small>
  <ol reversed class="mt-3">
    <% @tag.posts.each do |p| %>
    <li>
    <div class="row">
        <div class="col-12 col-xl-6">
            <%= link_to p.title, p %>
        </div>
        <div class="col-12 col-xl-6">
            <small class="text-muted">Created: <%= date(p.created_at) %> | Updated: <%= date(p.updated_at) %></small>
        </div>
    </div>
    </li>
    <% end %>
    </p>
  </ol>


<p class="mt-1">
  <%= link_to 'Back', tags_path, class: "btn btn-sm btn-outline-primary" %>
  <% if admin? %>
    <%= link_to 'Edit', edit_tag_path(@tag), class: "btn btn-sm btn-outline-primary" %>
  <% end %>
</p>