config/routes.rb
# typed: strict


Rails.application.routes.draw do
  resources :projects
  root 'static#index'
  get 'login', to: 'sessions#new'
  get 'portfolio', to: 'projects#index'
  get 'posts/list'
  get 'sessions/new'
  get 'setup/ubuntu'
  get 'setup/zsh'
  get 'setup/ruby'
  get 'setup/vscode'
  get 'setup/gnome'
  get 'setup/albert'
  get 'setup/index'
  get 'setup/misc'
  get 'setup/issues'
  get 'static/index'
  get 'static/aboutme'
  get 'contact', to: 'messages#new'
  get 'messages/new'
  post 'messages/create'
  resources :tags
  resources :sessions, only: %i[create new destroy]
  resources :posts
  get '/check.txt', to: proc { [200, {}, ['it_works']] }
  get 'google5ef096ebdd0ff65a.html', to: 'static#google5ef096ebdd0ff65a', layout: false
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# typed: strict


class Post < ApplicationRecord
  extend T::Sig

  has_many :taggings
  has_many :tags, through: :taggings

  sig { params(name: String).returns(T::Array[Tag]) }
  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  sig { returns(Tag::Relation) }
  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  sig { returns(String) }
  def tag_list
    tags.map(&:name).join(', ')
  end

  sig { params(names: String).void}
  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/posts_controller.rb
# typed: true

require 'will_paginate/array'

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authentication_required!, except: %i[index list show]

  # GET /posts
  def index
    @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 3)
  end

  def list
    @posts = Post.all.order(created_at: :asc)
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Post was successfully saved.'
      redirect_to @post
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      flash[:success] = 'Post was successfully updated.'
      redirect_to @post
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy

    flash[:info] = 'Post was successfully destroyed.'
    redirect_to posts_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(
      :title, :content, :user_id, :tag_list, :tag, { tag_ids: [] }, :tag_ids
    )
  end
end

app/helpers/posts_helper.rb
# typed: ignore


include ApplicationHelper

module PostsHelper
  def markdown_text(text)
    Redcarpet::Markdown.new(MarkdownRender, fenced_code_blocks: true,
                                            tables: true).render(text).html_safe
  end

  def active_tab(pages, title)
    if pages == title
      'nav-link bg-grey1 text-grey5'
    else
      'nav-link bg-grey2 text-grey4'
    end
  end

  def show_page
    !params[:id].nil?
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
<div class="row">
  <div class='col-md-8'>
    <%= f.input :title %>
    <%= f.input :content, input_html: { rows: 18 } %>
  </div>
  <div class="col-md-4">
    <%= f.input :tag_ids, as: :select, collection: Tag.order(:name), label_method: :name, input_html: {multiple: true, size: 20} %>
    <%= f.submit "Save", class: 'btn btn-lg btn-outline-primary float-right' %>
  </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="<%= 'd-flex' if !show_page %>">
  <% if show_page %>
  <h1><%= post.title %></h1>
  <p class="mb-2">
    <small class="text-muted">Created: <%= post.created_at.to_formatted_s(:long) %> | Updated:
      <%= post.updated_at.to_formatted_s(:long) %><br>
      Tags: <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small>
  </p>
  <% end %>
  <div class="mb-4 flex-fill rounded-left bg-grey0 p-3 shadow-sm markdown">
    <% if show_page %>
    <%= render partial: 'layouts/post_admin_buttons', locals: {post: post, admin: admin?}%>
    <% end %>
    <% if !show_page %>
    <%= link_to(post, html_options = {}) do %>
    <h2><%= post.title %></h2>
    <% end %>

    <small class="text-muted">Created: <%= date(post.created_at) %> | Updated: <%= date(post.updated_at) %><br>
      Tags: <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small>

    <% end %>

    <% if !show_page %>
    <small class="text-muted"><%= markdown_text(post.content.truncate(200)) %></small>
    <p><%= link_to 'View Post', post, class: "btn btn-sm btn-outline-secondary"%>
      <%= render partial: 'layouts/post_admin_buttons', locals: {post: post, admin: admin? }%>
    </p>
    <% else %>
    <p><%= markdown_text(post.content) %></p>
    <% end %>
    <% if show_page %>
    <p><small class="text-muted">Written by <%= link_to 'Alan Vardy', contact_path %>. Let me know how I can make this
        better!</small></p>
    <% end %>
  </div>
  <div class="<%= 'rounded-right bg-secondary px-1 mb-4' if !show_page %>">
  </div>
  <div class="<%= 'px-3' if !show_page %>">
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, 'Edit Post') %>
<%= render 'layouts/top_of_page' %>

<h1>Edit Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% provide(:title, "Blog") %>
<%= render 'layouts/post_tabs' %>


<h1>Latest Posts</h1>
<%= will_paginate %>
<%= render @posts %>
<%= will_paginate %>

app/views/posts/list.html.erb
<% provide(:title, "All Posts") %>
<%= render 'layouts/post_tabs' %>
<h1>All Posts</h1>
<div class="border-secondary pl-2 border-left">
    <ol>
        <% @posts.each do |p| %>
        <li >
        <div class="row">
            <div class="col-12 col-xl-6">
                <%= link_to p.title, p %>
            </div>
            <div class="col-12 col-xl-6">
                <small class="text-muted">Created: <%= p.created_at.to_formatted_s(:long) %> | Updated: <%= p.updated_at.to_formatted_s(:long) %></small>
            </div>
        </div>
        </li>
        <% end %>
    </ol>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>
<%= render 'layouts/top_of_page' %>

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% provide(:title, "Blog") %>
<%= render 'layouts/top_of_page' %>
<%= render @post %>