config/routes.rb
# typed: strict


Rails.application.routes.draw do
  resources :projects
  root 'static#index'
  get 'login', to: 'sessions#new'
  get 'portfolio', to: 'projects#index'
  get 'posts/list'
  get 'sessions/new'
  get 'setup/ubuntu'
  get 'setup/zsh'
  get 'setup/ruby'
  get 'setup/vscode'
  get 'setup/gnome'
  get 'setup/albert'
  get 'setup/index'
  get 'setup/misc'
  get 'setup/issues'
  get 'static/index'
  get 'static/aboutme'
  get 'contact', to: 'messages#new'
  get 'messages/new'
  post 'messages/create'
  resources :tags
  resources :sessions, only: %i[create new destroy]
  resources :posts
  get '/check.txt', to: proc { [200, {}, ['it_works']] }
  get 'google5ef096ebdd0ff65a.html', to: 'static#google5ef096ebdd0ff65a', layout: false
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/setup_controller.rb
# typed: true


class SetupController < ApplicationController
  def ubuntu; end

  def zsh; end

  def ruby; end

  def vscode; end

  def gnome; end

  def index; end
end

app/helpers/setup_helper.rb
# typed: ignore
include ApplicationHelper

module SetupHelper
  def markdown_file(filename)
    path = Rails.root.join('app', 'assets', 'markdowns', filename)
    text = File.read(path)
    Redcarpet::Markdown.new(MarkdownRender, fenced_code_blocks: true).render(text).html_safe
  end
end

app/views/setup/albert.html.erb
<% provide(:title, "Albert") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, "Zsh") %>
<% provide(:back_path, setup_zsh_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'Visual Studio Code') %>
<% provide(:forward_path, setup_vscode_path) %>

<%= render 'layouts/nav_buttons' %>

<%= render 'layouts/mdimage', locals: {folder: "setup", filename: "albert.png"} %>
<%= markdown_file('albert.md') %>

<%= render 'layouts/nav_buttons' %>

app/views/setup/gnome.html.erb
<% provide(:title, "Gnome") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, "Ubuntu Linux") %>
<% provide(:back_path, setup_ubuntu_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'rbenv and Ruby') %>
<% provide(:forward_path, setup_ruby_path) %>

<%= render 'layouts/nav_buttons' %>

<%= render 'layouts/mdimage', locals: {folder: "setup", filename: "gnome.svg"} %>
<%=  markdown_file('gnome.md') %>

<%= render 'layouts/nav_buttons' %>

app/views/setup/index.html.erb
<% provide(:title, "Setup") %>
<%= render 'layouts/top_of_page' %>

<h1>Setting up my Developer Environment</h1>
<%= render 'layouts/lgimage', locals: {folder: "setup", filename: "battlestation.jpg"} %>
<div class="row">
    <div class="col-12 col-md-6">
        <p>
            One of my vices is spending plenty of time installing and reinstalling operating systems, tools, and plugins.
        </p>
        <p>
            I'm using this section of the website as a living record of the current state of my developer environment in the hopes
            that it may be useful to someone else as well!
        </p>
    </div>
    <div class="col-12 col-md-6">
        <ol class="border-secondary border-left">
            <li><%= link_to 'Ubuntu Linux', setup_ubuntu_path %></li>
            <li><%= link_to 'Gnome Settings', setup_gnome_path %></li>
            <li><%= link_to 'rbenv and Ruby', setup_ruby_path %></li>
            <li><%= link_to 'Zsh', setup_zsh_path %></li>
            <li><%= link_to 'Albert', setup_albert_path %></li>
            <li><%= link_to 'Visual Studio Code', setup_vscode_path %></li>
            <li><%= link_to 'Miscellaneous', setup_misc_path %></li>
            <li><%= link_to 'Issues', setup_issues_path %></li>
        </ol>
    </div>
</div>

app/views/setup/issues.html.erb
<% provide(:title, "Issues") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, "Miscellaneous") %>
<% provide(:back_path, setup_misc_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'Setup') %>
<% provide(:forward_path, setup_index_path) %>

<%= render 'layouts/nav_buttons' %>

<%=  markdown_file('issues.md') %>

<%= render 'layouts/nav_buttons' %>

app/views/setup/misc.html.erb
<% provide(:title, "Misc") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, "Visual Studio Code") %>
<% provide(:back_path, setup_gnome_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'Issues') %>
<% provide(:forward_path, setup_issues_path) %>

<%= render 'layouts/nav_buttons' %>

<%=  markdown_file('misc.md') %>

<%= render 'layouts/nav_buttons' %>

app/views/setup/ruby.html.erb
<% provide(:title, "rbenv and Ruby") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, "Gnome Settings") %>
<% provide(:back_path, setup_gnome_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'Zsh') %>
<% provide(:forward_path, setup_zsh_path) %>

<%= render 'layouts/nav_buttons' %>

<%= render 'layouts/mdimage', locals: {folder: "setup", filename: "ruby.png"} %>
<%= markdown_file('ruby.md') %>

<%= render 'layouts/nav_buttons' %>

app/views/setup/ubuntu.html.erb
<% provide(:title, "Ubuntu") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, 'Setup') %>
<% provide(:back_path, setup_index_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'Gnome Settings') %>
<% provide(:forward_path, setup_gnome_path) %>

<%= render 'layouts/nav_buttons' %>

<%= render 'layouts/mdimage', locals: {folder: "setup", filename: "ubuntuxps.png"} %>
<%=  markdown_file('ubuntu.md') %>

<%= render 'layouts/nav_buttons' %>

app/views/setup/vscode.html.erb
<% provide(:title, "VS Code") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, "Albert") %>
<% provide(:back_path, setup_albert_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'Miscellaneous') %>
<% provide(:forward_path, setup_misc_path) %>

<%= render 'layouts/nav_buttons' %>

<%= render 'layouts/lgimage', locals: {folder: "setup", filename: "vscode.png"} %>
<%=  markdown_file('vscode.md') %>

<%= render 'layouts/nav_buttons' %>

app/views/setup/zsh.html.erb
<% provide(:title, "Zsh") %>
<%= render 'layouts/top_of_page' %>

<% provide(:back, "rbenv and Ruby") %>
<% provide(:back_path, setup_ruby_path) %>
<% provide(:up, "Setup") %>
<% provide(:up_path, setup_index_path) %>
<% provide(:forward, 'Albert') %>
<% provide(:forward_path, setup_albert_path) %>

<%= render 'layouts/nav_buttons' %>

<%= render 'layouts/mdimage', locals: {folder: "setup", filename: "zsh.png"} %>
<%=  markdown_file('zsh.md') %>

<%= render 'layouts/nav_buttons' %>