config/routes.rb
# typed: strict


Rails.application.routes.draw do
  resources :projects
  root 'static#index'
  get 'login', to: 'sessions#new'
  get 'portfolio', to: 'projects#index'
  get 'posts/list'
  get 'sessions/new'
  get 'setup/ubuntu'
  get 'setup/zsh'
  get 'setup/ruby'
  get 'setup/vscode'
  get 'setup/gnome'
  get 'setup/albert'
  get 'setup/index'
  get 'setup/misc'
  get 'setup/issues'
  get 'static/index'
  get 'static/aboutme'
  get 'contact', to: 'messages#new'
  get 'messages/new'
  post 'messages/create'
  resources :tags
  resources :sessions, only: %i[create new destroy]
  resources :posts
  get '/check.txt', to: proc { [200, {}, ['it_works']] }
  get 'google5ef096ebdd0ff65a.html', to: 'static#google5ef096ebdd0ff65a', layout: false
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# typed: strong
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# typed: true
require 'mailgun-ruby'

# For sending mailgun messages from the contact page
class Message
  extend T::Sig
  include ActiveModel::Model

  attr_accessor :name, :email, :phone_number, :body
  validates :name, :body, presence: true
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  sig { void }
  def send
    mg_client = Mailgun::Client.new ENV['mailgun_secret_api_key']
    mg_client.enable_test_mode! if Rails.env.test?
    info = {
      from: email,
      to: 'alan@alanvardy.com',
      subject: "Email from #{name} - alanvardy.com",
      text: "From: #{name}, Email: #{email}, Phone: #{phone_number} \n\n #{body}"
    }
    mg_client.send_message 'mg.alanvardy.com', info
  end
end

app/models/post.rb
# typed: strict


class Post < ApplicationRecord
  extend T::Sig

  has_many :taggings
  has_many :tags, through: :taggings

  sig { params(name: String).returns(T::Array[Tag]) }
  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  sig { returns(Tag::Relation) }
  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  sig { returns(String) }
  def tag_list
    tags.map(&:name).join(', ')
  end

  sig { params(names: String).void}
  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/project.rb
# typed: strict

class Project < ApplicationRecord
  extend T::Sig

  validates :giturl, presence: true

  sig { returns(String) }
  def picture_url
    return T.must(more) if more.present?
    return T.must(weburl) if weburl.present?

    T.must(giturl)
  end

  sig { returns(T::Boolean) }
  def weburl?
    !weburl.empty?
  end

  sig { returns(T::Boolean) }
  def giturl?
    !giturl.empty?
  end
end

app/models/project_technology.rb
# frozen_string_literal: true

class ProjectTechnology < ApplicationRecord
  belongs_to :project
  belongs_to :technology
end

app/models/tag.rb
# typed: strict
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
# typed: strong
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/technology.rb
# frozen_string_literal: true

class Technology < ApplicationRecord
  has_many :projects, through: :project_technologies
end

app/models/user.rb
# typed: true
class User
  extend T::Sig
  include ActiveModel::Model

  attr_accessor :username, :password

  sig { returns(T::Boolean) }
  def login_valid?
    if Rails.env.test?
      @username == 'foo' && @password == 'bar'
    else
      @username == (ENV['ADMIN_USERNAME']) && @password == (ENV['ADMIN_PASS'])
    end
  end
end

app/controllers/posts_controller.rb
# typed: true

require 'will_paginate/array'

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authentication_required!, except: %i[index list show]

  # GET /posts
  def index
    @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 3)
  end

  def list
    @posts = Post.all.order(created_at: :asc)
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Post was successfully saved.'
      redirect_to @post
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      flash[:success] = 'Post was successfully updated.'
      redirect_to @post
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy

    flash[:info] = 'Post was successfully destroyed.'
    redirect_to posts_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(
      :title, :content, :user_id, :tag_list, :tag, { tag_ids: [] }, :tag_ids
    )
  end
end

app/controllers/setup_controller.rb
# typed: true


class SetupController < ApplicationController
  def ubuntu; end

  def zsh; end

  def ruby; end

  def vscode; end

  def gnome; end

  def index; end
end

app/controllers/tags_controller.rb
# typed: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]
  before_action :authentication_required!, except: %i[index show]

  # GET /tags
  def index
    @tags = Tag.all.order(name: :asc)
  end

  # GET /tags/1
  def show; end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = 'Tag was successfully created.'
      redirect_to @tag
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      flash[:success] = 'Tag was successfully updated.'
      redirect_to @tag
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    flash[:success] = 'Tag was successfully destroyed.'
    redirect_to tags_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find_by(name: params[:id]) || Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
# typed: false


module ApplicationHelper
  require 'redcarpet'
  require 'rouge'
  require 'rouge/plugins/redcarpet'
  # Custom renderer for Markdown syntax
  class MarkdownRender < Redcarpet::Render::HTML
    def initialize(extensions = {})
      super extensions.merge(link_attributes: { target: 'blank' })
    end
    include Rouge::Plugins::Redcarpet
  end

  def date(sequence)
    sequence.strftime('%F')
  end

  def active_nav(pages, title)
    if pages.include?(title)
      'nav-item nav-link active'
    else
      'nav-item nav-link'
    end
  end

  def admin?
    session[:current_user]
  end
end

app/helpers/posts_helper.rb
# typed: ignore


include ApplicationHelper

module PostsHelper
  def markdown_text(text)
    Redcarpet::Markdown.new(MarkdownRender, fenced_code_blocks: true,
                                            tables: true).render(text).html_safe
  end

  def active_tab(pages, title)
    if pages == title
      'nav-link bg-grey1 text-grey5'
    else
      'nav-link bg-grey2 text-grey4'
    end
  end

  def show_page
    !params[:id].nil?
  end
end

app/helpers/projects_helper.rb
# typed: strong
module ProjectsHelper
end

app/helpers/sessions_helper.rb
# typed: strong
module SessionsHelper
end

app/helpers/setup_helper.rb
# typed: ignore
include ApplicationHelper

module SetupHelper
  def markdown_file(filename)
    path = Rails.root.join('app', 'assets', 'markdowns', filename)
    text = File.read(path)
    Redcarpet::Markdown.new(MarkdownRender, fenced_code_blocks: true).render(text).html_safe
  end
end

app/helpers/static_helper.rb
# typed: strong
module StaticHelper
end

app/helpers/tags_helper.rb
# typed: strong
module TagsHelper
end

app/helpers/technologies_helper.rb
# frozen_string_literal: true

module TechnologiesHelper
end

app/views/layouts/_analytics.html.erb
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-131114774-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-131114774-1');
</script>

app/views/layouts/_call_to_action.html.erb
<div class="d-flex justify-content-center pt-4 mt-4 border-top border-secondary">
    Like what you see?
</div>
<div class="d-flex justify-content-center mt-3">
    <%= link_to 'Contact me!', contact_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/layouts/_footer.html.erb
<div class="bg-dark mb-3 py-1 px-2 container rounded-bottom">
    <div class="row">
        <div class="col-12 col-md-6 d-flex justify-content-between justify-content-md-start">
            <a href="mailto:alan@alanvardy.com" class="nostyle"><i class="fas fa-copyright mr-1"></i><small> <%= Time.now.year %> Alan Vardy</small></a>
            <%= link_to(login_path, html_options = { class: "nostyle ml-md-3" }) do %>
                <i class="fas fa-lock mr-1"></i><small> Admin Login</small>
            <% end %>
        </div>

        <div class="col-12 col-md-6 d-flex justify-content-between justify-content-md-end">
            <a href="https://github.com/alanvardy/" class="nostyle mr-md-3"><i class="fab fa-github-square mr-1"></i><small> Github</small></i></a>
            <a href="mailto:alanvardy@gmail.com" class="nostyle"><i class="fas fa-envelope-square mr-1"></i><small> Email Me</small></i></a>
        </div>
    </div>
</div>

app/views/layouts/_lgimage.html.erb
<%= image_tag "#{locals[:folder]}/#{locals[:filename]}", class: 'rounded w-100 d-block d-sm-none mx-auto mb-5 mt-2 shadow-sm' %>
<%= image_tag "#{locals[:folder]}/#{locals[:filename]}", class: 'rounded w-75 d-none d-sm-block mx-auto mb-5 mt-2 shadow-sm' %>

app/views/layouts/_mdimage.html.erb
<%= image_tag "#{locals[:folder]}/#{locals[:filename]}", class: 'rounded w-75 d-block d-md-none mx-auto mb-5 mt-2 shadow-sm' %>
<%= image_tag "#{locals[:folder]}/#{locals[:filename]}", class: 'rounded w-50 d-none d-md-block mx-auto mb-5 mt-2 shadow-sm' %>

app/views/layouts/_nav_buttons.html.erb
 <div class="row my-3">
  <div class="order-2 order-sm-1 col-6 col-sm-4 d-flex justify-content-start my-3">
    <%= link_to yield(:back_path), class: 'btn btn-sm btn-outline-primary' do %>
      <i class="fas fa-arrow-left"></i> <%= yield(:back) %>
    <% end %>
  </div>
  <div class="order-1 order-sm-2 col-12 col-sm-4 d-sm-flex d-none justify-content-center my-3">
    <%= link_to yield(:up_path), class: 'btn btn-sm btn-outline-primary' do %>
      <i class="fas fa-arrow-up"></i> <%= yield(:up) %>
    <% end %>
  </div>
  <div class="order-3 col -6 col-sm-4 d-flex justify-content-end my-3">
    <%= link_to yield(:forward_path), class: 'btn btn-sm btn-outline-primary' do %>
      <i class="fas fa-arrow-right"></i> <%= yield(:forward) %>
    <% end %>
  </div>
 </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-sm navbar-dark bg-dark">
  <%= link_to 'alanvardy', root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav mr-auto">
    <%= link_to 'Home', root_path, class: active_nav('Home', yield(:title)) %>
    <%= link_to 'Blog', posts_path, class: active_nav(['Blog', 'Tags', 'All Posts'], yield(:title)) %>
    <%= link_to 'Portfolio', portfolio_path, class: active_nav('Portfolio', yield(:title)) %>
    <%= link_to 'My Setup', setup_index_path, class: active_nav('My Setup', yield(:title)) %>
    <%= link_to 'About Me', static_aboutme_path, class: active_nav('About Me', yield(:title)) %>
    <%= link_to 'Contact Me', contact_path, class: active_nav('Contact Me', yield(:title)) %>
    </div>
    <div class="navbar-nav">
      <% if admin? %>
        <%= link_to 'New Project', new_project_path, class: "btn btn-sm btn-info ml-2" %>
        <%= link_to 'New Post', new_post_path, class: "btn btn-sm btn-info ml-2" %>
        <%= link_to 'Log out', session_path('logout'), method: :delete, class: 'btn btn-sm btn-info ml-2' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_post_admin_buttons.html.erb
<% if admin %>
    <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-sm btn-outline-warning' %>
    <%= link_to 'Destroy', post, method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/layouts/_post_tabs.html.erb
  <div class="container mt-2">
<ul class="nav nav-tabs border-0">
  <li class="nav-item">
  <%= link_to 'Latest Posts', posts_path, class: active_tab("Blog", yield(:title)) %>
  </li>
  <li class="nav-item">
    <%= link_to 'Tags', tags_path, class: active_tab("Tags", yield(:title)) %>
  </li>
  <li class="nav-item">
    <%= link_to 'All Posts', posts_list_path, class: active_tab("All Posts", yield(:title)) %>
  </li>

</ul>
</div>
  <div class="container rounded-top bg-grey1 px-3 px-md-5 mt-0 py-5">
  <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_top_of_page.html.erb
  <div class="container bg-grey1 mt-sm-5 mt-1 rounded-top py-5 px-md-5 px-3">
  <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | alanvardy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon/favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="EwCnP-VfUtPkErB2S8_EsHiFUuj_D5xENrmMT44YFwY" />
    <%= render 'layouts/analytics' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-grey3 text-dark">
  <%= render 'layouts/navbar' %>
    <%= yield %>

  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>